version: 0.2

phases:
  install:
    commands:
       - docker build -t myapp .
       - docker run myapp
  pre_build:
    commands:
      - echo Build started
  build:
    commands:
      - docker build -t myapp .
      - docker run myapp
  post_build:
    commands:
      - echo Build completed
